apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: whoami
      app.kubernetes.io/part-of: example-app
    includeSelectors: true
